export const products = [
  {
    id: 1,
    name: "Colar Dourado Eterno",
    category: "colares",
    price: 289,
    description: "Colar artesanal em ouro 18k com acabamento escovado. Peça de edição limitada.",
    image: "/images/pd-01.jpeg",
    materials: "Ouro 18k, acabamento escovado",
    dimensions: "45 cm + 5 cm extensão",
    badge: "Bestseller",
    featured: true,
  },
  {
    id: 2,
    name: "Brincos Madeira & Ouro",
    category: "brincos",
    price: 189,
    description: "Brincos exclusivos combinando madeira nobre e ouro artesanal.",
    image: "/images/pd-02.jpeg",
    materials: "Madeira Mogno, Ouro 18k",
    dimensions: "3.5 cm comprimento",
    badge: "Novo",
    featured: true,
  },
  {
    id: 3,
    name: "Pulseira Clássica Dourada",
    category: "pulseiras",
    price: 249,
    description: "Pulseira elegante em tom dourado, feita à mão com técnica tradicional.",
    image: "/images/pd-03.jpeg",
    materials: "Ouro 18k",
    dimensions: "18 cm ajustável",
    badge: null,
    featured: true,
  },
  {
    id: 4,
    name: "Anel Solitário",
    category: "aneis",
    price: 320,
    description: "Anel solitário em ouro com pedra semipreciosa natural. Peça única.",
    image: "/images/pd-04.jpeg",
    materials: "Ouro 18k, Topázio",
    dimensions: "Tamanhos 14–22",
    badge: "Exclusivo",
    featured: true,
  },
  {
    id: 5,
    name: "Conjunto Madeira Dourada",
    category: "conjuntos",
    price: 450,
    description: "Conjunto completo — colar, brincos e pulseira em harmonia artesanal.",
    image: "/images/pd-05.jpeg",
    materials: "Madeira Teca, Ouro 18k",
    dimensions: "Peças individuais ajustáveis",
    badge: "Edição Limitada",
    featured: true,
  },
  {
    id: 6,
    name: "Brincos Folha Natural",
    category: "brincos",
    price: 165,
    description: "Brincos inspirados na natureza, com folha em ouro martelado.",
    image: "/images/pd-06.jpeg",
    materials: "Ouro 18k martelado",
    dimensions: "4 cm comprimento",
    badge: null,
    featured: true,
  },
  {
    id: 7,
    name: "Colar Gota Âmbar",
    category: "colares",
    price: 275,
    description: "Colar com pingente gota em âmbar natural envolto em fio dourado.",
    image: "/images/pd-07.jpeg",
    materials: "Âmbar natural, Ouro 18k",
    dimensions: "42 cm",
    badge: null,
    featured: true,
  },
  {
    id: 8,
    name: "Pulseira Dupla Elegância",
    category: "pulseiras",
    price: 198,
    description: "Pulseira dupla em ouro com detalhe em madeira entalhada.",
    image: "/images/pd-08.jpeg",
    materials: "Ouro 18k, Madeira Ipê",
    dimensions: "17 cm ajustável",
    badge: "Novo",
    featured: true,
  },
  {
    id: 9,
    name: "Anel Infinito",
    category: "aneis",
    price: 215,
    description: "Anel símbolo do infinito, esculpido em ouro sólido. Significado eterno.",
    image: "/images/pd-09.jpeg",
    materials: "Ouro 18k",
    dimensions: "Tamanhos 14–22",
    badge: null,
    featured: false,
  },
  {
    id: 10,
    name: "Colar Madeira Escura",
    category: "colares",
    price: 310,
    description: "Colar statement com contas de madeira escura e detalhes dourados.",
    image: "/images/pd-10.jpeg",
    materials: "Madeira Ébano, Ouro 18k",
    dimensions: "50 cm",
    badge: null,
    featured: false,
  },
  {
    id: 11,
    name: "Brincos Argola Clássica",
    category: "brincos",
    price: 145,
    description: "Argolas clássicas em ouro escovado. Peça essencial de qualquer coleção.",
    image: "/images/pd-11.jpeg",
    materials: "Ouro 18k escovado",
    dimensions: "2.5 cm diâmetro",
    badge: null,
    featured: false,
  },
  {
    id: 12,
    name: "Conjunto Nupcial",
    category: "conjuntos",
    price: 680,
    description: "Conjunto especial para momentos únicos. Colar e brincos em harmonia perfeita.",
    image: "/images/pd-12.jpeg",
    materials: "Ouro 18k, Pérolas naturais",
    dimensions: "Peças individuais",
    badge: "Coleção Especial",
    featured: false,
  },
];

export const categories = [
  { id: "colares", name: "Colares", image: "/images/pd-07.jpeg", count: 3 },
  { id: "brincos", name: "Brincos", image: "/images/pd-02.jpeg", count: 4 },
  { id: "pulseiras", name: "Pulseiras", image: "/images/pd-03.jpeg", count: 3 },
  { id: "aneis", name: "Anéis", image: "/images/pd-04.jpeg", count: 3 },
  { id: "conjuntos", name: "Conjuntos", image: "/images/pd-05.jpeg", count: 2 },
];

export const testimonials = [
  {
    id: 1,
    name: "Sofia Mendes",
    role: "Designer de Moda",
    text: "As peças ANCÉS são simplesmente extraordinárias. O cuidado artesanal em cada detalhe é visível e sentido. Uso todos os dias com orgulho.",
    image: "/images/pd-13.jpeg",
    rating: 5,
  },
  {
    id: 2,
    name: "Mariana Costa",
    role: "Empresária",
    text: "Recebi o conjunto como presente e fiquei rendida. A qualidade dos materiais e a elegância do design falam por si. Uma marca verdadeiramente única.",
    image: "/images/pd-14.jpeg",
    rating: 5,
  },
  {
    id: 3,
    name: "Ana Ferreira",
    role: "Arquiteta",
    text: "Descobri a ANCÉS há dois anos e desde então é a minha marca de eleição. Cada peça conta uma história e transmite uma energia especial.",
    image: "/images/pd-15.jpeg",
    rating: 5,
  },
];

export const essence = [
  {
    icon: "✦",
    title: "Artesanal",
    description: "Cada peça é criada à mão por artesãos com décadas de experiência, garantindo unicidade e perfeição em cada detalhe.",
  },
  {
    icon: "◈",
    title: "Materiais Premium",
    description: "Selecionamos apenas os melhores materiais — ouro 18k, madeiras nobres, pedras semipreciosas naturais — para criar joias de durabilidade inigualável.",
  },
  {
    icon: "◇",
    title: "Edição Limitada",
    description: "As nossas coleções são produzidas em séries muito limitadas, assegurando que cada cliente possui uma peça verdadeiramente exclusiva.",
  },
  {
    icon: "○",
    title: "Entrega Segura",
    description: "Cada joia é embalada com o mesmo cuidado com que é criada, e entregue com total segurança e discrição, onde quer que esteja.",
  },
];
