const PRODUCTS = [
  {
    id: 1,
    name: "Colar Dourado Eterno",
    category: "colares",
    categoryLabel: "Colares",
    price: 289,
    description: "Colar artesanal em ouro 18k com acabamento escovado. Peça de edição limitada.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.44 (1).jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.44 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.44 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (1).jpeg",
    ],
    materials: "Ouro 18k, acabamento escovado",
    dimensions: "45 cm + 5 cm extensão",
    care: "Evite contacto com água e perfume. Limpe com pano macio.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: "Bestseller",
    featured: true,
  },
  {
    id: 2,
    name: "Brincos Madeira & Ouro",
    category: "brincos",
    categoryLabel: "Brincos",
    price: 189,
    description: "Brincos exclusivos combinando madeira nobre e ouro artesanal.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.44 (2).jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.44 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (2).jpeg",
    ],
    materials: "Madeira Mogno, Ouro 18k",
    dimensions: "3.5 cm comprimento",
    care: "Guarde num local seco. Evite humidade.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: "Novo",
    featured: true,
  },
  {
    id: 3,
    name: "Pulseira Clássica Dourada",
    category: "pulseiras",
    categoryLabel: "Pulseiras",
    price: 249,
    description: "Pulseira elegante em tom dourado, feita à mão com técnica tradicional.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.45.jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46.jpeg",
    ],
    materials: "Ouro 18k",
    dimensions: "18 cm ajustável",
    care: "Evite contacto com cloro e perfume.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: null,
    featured: true,
  },
  {
    id: 4,
    name: "Anel Solitário",
    category: "aneis",
    categoryLabel: "Anéis",
    price: 320,
    description: "Anel solitário em ouro com pedra semipreciosa natural. Peça única.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (1).jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (1).jpeg",
    ],
    materials: "Ouro 18k, Topázio",
    dimensions: "Tamanhos 14–22",
    care: "Guarde separado de outras peças.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: "Exclusivo",
    featured: true,
  },
  {
    id: 5,
    name: "Conjunto Madeira Dourada",
    category: "conjuntos",
    categoryLabel: "Conjuntos",
    price: 450,
    description: "Conjunto completo — colar, brincos e pulseira em harmonia artesanal.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (2).jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.45 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (2).jpeg",
    ],
    materials: "Madeira Teca, Ouro 18k",
    dimensions: "Peças individuais ajustáveis",
    care: "Cada peça requer cuidados específicos — ver instruções inclusas.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: "Edição Limitada",
    featured: true,
  },
  {
    id: 6,
    name: "Brincos Folha Natural",
    category: "brincos",
    categoryLabel: "Brincos",
    price: 165,
    description: "Brincos inspirados na natureza, com folha em ouro martelado.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.46.jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47.jpeg",
    ],
    materials: "Ouro 18k martelado",
    dimensions: "4 cm comprimento",
    care: "Limpe com pano de microfibra.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: null,
    featured: true,
  },
  {
    id: 7,
    name: "Colar Gota Âmbar",
    category: "colares",
    categoryLabel: "Colares",
    price: 275,
    description: "Colar com pingente gota em âmbar natural envolto em fio dourado.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (1).jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (1).jpeg",
    ],
    materials: "Âmbar natural, Ouro 18k",
    dimensions: "42 cm",
    care: "Evite exposição direta ao sol por longos períodos.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: null,
    featured: true,
  },
  {
    id: 8,
    name: "Pulseira Dupla Elegância",
    category: "pulseiras",
    categoryLabel: "Pulseiras",
    price: 198,
    description: "Pulseira dupla em ouro com detalhe em madeira entalhada.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (2).jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.46 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (2).jpeg",
    ],
    materials: "Ouro 18k, Madeira Ipê",
    dimensions: "17 cm ajustável",
    care: "Evite contacto com produtos químicos.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: "Novo",
    featured: true,
  },
  {
    id: 9,
    name: "Anel Infinito",
    category: "aneis",
    categoryLabel: "Anéis",
    price: 215,
    description: "Anel símbolo do infinito, esculpido em ouro sólido. Significado eterno.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.47.jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48.jpeg",
    ],
    materials: "Ouro 18k",
    dimensions: "Tamanhos 14–22",
    care: "Limpe com pano macio. Guarde num estojo.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: null,
    featured: false,
  },
  {
    id: 10,
    name: "Colar Madeira Escura",
    category: "colares",
    categoryLabel: "Colares",
    price: 310,
    description: "Colar statement com contas de madeira escura e detalhes dourados.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (1).jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48 (1).jpeg",
    ],
    materials: "Madeira Ébano, Ouro 18k",
    dimensions: "50 cm",
    care: "Evite humidade excessiva.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: null,
    featured: false,
  },
  {
    id: 11,
    name: "Brincos Argola Clássica",
    category: "brincos",
    categoryLabel: "Brincos",
    price: 145,
    description: "Argolas clássicas em ouro escovado. Peça essencial de qualquer coleção.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (2).jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.47 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48 (2).jpeg",
    ],
    materials: "Ouro 18k escovado",
    dimensions: "2.5 cm diâmetro",
    care: "Limpe regularmente com pano suave.",
    availability: "Em Stock — Envio em 2–3 dias úteis",
    badge: null,
    featured: false,
  },
  {
    id: 12,
    name: "Conjunto Nupcial",
    category: "conjuntos",
    categoryLabel: "Conjuntos",
    price: 680,
    description: "Conjunto especial para momentos únicos. Colar e brincos em harmonia perfeita.",
    image: "images-pd/WhatsApp Image 2026-09-06 at 22.13.48.jpeg",
    images: [
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48.jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48 (1).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48 (2).jpeg",
      "images-pd/WhatsApp Image 2026-09-06 at 22.13.48 (3).jpeg",
    ],
    materials: "Ouro 18k, Pérolas naturais",
    dimensions: "Peças individuais",
    care: "Conserve no estojo original.",
    availability: "Encomenda Especial — 5–7 dias úteis",
    badge: "Coleção Especial",
    featured: false,
  },
];

const CATEGORIES = [
  { id: "colares",   label: "Colares" },
  { id: "brincos",   label: "Brincos" },
  { id: "pulseiras", label: "Pulseiras" },
  { id: "aneis",     label: "Anéis" },
  { id: "conjuntos", label: "Conjuntos" },
];

function formatPrice(price) {
  return price.toLocaleString("pt-PT", { style: "currency", currency: "EUR", minimumFractionDigits: 0 });
}

function productCardHTML(p) {
  return `
    <a href="produto.html?id=${p.id}" class="product-card">
      <div class="product-card__img">
        <img src="${p.image}" alt="${p.name}" loading="lazy" />
        ${p.badge ? `<span class="product-card__badge">${p.badge}</span>` : ""}
        <div class="product-card__overlay"><span>Ver Detalhes</span></div>
      </div>
      <div class="product-card__info">
        <span class="product-card__cat">${p.categoryLabel}</span>
        <h3 class="product-card__name">${p.name}</h3>
        <p class="product-card__desc">${p.description}</p>
        <p class="product-card__price">${formatPrice(p.price)}</p>
      </div>
    </a>
  `;
}
